### ISSUE TITLE
 Pandoc died with exitcode "9" during conversion: b'pandoc: Unknown writer: pdf

### ISSUE THREAD

**Issue by zero323** [bebraw/pypandoc#100]
To be honest I have no idea where exactly is the problem here.  I have following piece of code:

```python
import pypandoc

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--fmt")
    parser.add_argument("--fail", dest="fail", action="store_true")
    parser.set_defaults(fail=False)
    args = parser.parse_args()

    if args.fail:
        to = args.fmt 
    else:
        # Ridiculous but works  
        to = "pdf" if args.fmt == "pdf" else args.fmt 

    pypandoc.convert(
        source="# Foo", to=to,
        format="markdown",
        outputfile="foo.pdf"
    )

if __name__ == "__main__":
    main()
```

which works just fine when I run it with `python ex2.py --fmt pdf` and let it use completely meaningless `"pdf" if args.fmt == "pdf" else args.fmt` but fails otherwise with 

```
RuntimeError: Pandoc died with exitcode "9" during conversion: b'pandoc: Unknown writer: pdf
To create a pdf with pandoc, use the latex or beamer writer and specify
an output file with .pdf extension (pandoc -t latex -o filename.pdf).'
```

Environment:

- Debian GNU/Linux
- Pandoc Version: 1.16.0.2~dfsg-1
- pypandoc==1.1.3
- Python  3.5.1, Python 2.7.11

**Comment by bebraw** [comment]
Yeah, sounds like something weird with our adaptation process. Looks like pandoc expects something extra for pdf these days so we probably should provide a separate parameter just for that. Then you could do `target="latex"` or whatever that `-t` maps to.

**Comment by janschulz** [comment]
The problem is that `to is not 'pdf'` is the wrong test, it should be `to != 'pdf'`

**Comment by janschulz** [comment]
I added the fix to https://github.com/bebraw/pypandoc/pull/96

**Comment by zero323** [comment]
@janschulz Thank you.

**Comment by janschulz** [comment]
```py
        # Ridiculous but works  
        to = "pdf" if args.fmt == "pdf" else args.fmt 
```

I think this works because python interns some strings: http://stackoverflow.com/questions/15541404/python-string-interning

**Comment by janschulz** [comment]
The worse bug is actually this:

```py
>>> pypandoc.convert_text(source="# Foo", to="pdf", format="markdown")
'<h1 id="foo">Foo</h1>\r\n'
```

**Comment by janschulz** [comment]
So, the PR is in #101 

If you need a workaround, use 

```
to = "latex" if args.fmt == "pdf" else args.fmt 
```
