### ISSUE TITLE
Support URL paths

### ISSUE THREAD

**Issue by dufferzafar** [bebraw/pypandoc#108]
The [`_identify_path`](https://github.com/bebraw/pypandoc/blob/master/pypandoc/__init__.py#L143) function doesn't treat web URLs as path, but it should.

pandoc supports stuff like: `pandoc https://www.xyplorer.com/whatsnew.php -o "file.pdf"`

**Comment by bebraw** [comment]
PR welcome. :+1:

**Comment by janschulz** [comment]
@dufferzafar Do you expect to use URLs instead of filenames somewhere?

I would be more inclined to go for a `convert_url(...)` function in line with the new `convert_file` and `convert_text()` and a `_identify_url()` function (using `urllib.parse.urlparse(url)` and the py2 equivalent).

**Comment by dufferzafar** [comment]
@janschulz Yes, I need to use it the URLs and that's how I found that pypandoc doesn't already handle it.

> But that has the "problem" that if your application UI does not distinguish between files and URLs, then this checking logic is duplicated in your app layer

This is very true. After looking at pypandoc's code I felt like a better way for me would be to just create a new "thinner" wrapper over pandoc, that just calls pandoc with some params.

**Comment by janschulz** [comment]
I would be open to a PR which adds such a `_identify_URL()` functions or modifies the current one to `_identify_file_or_url()`.

**Comment by janschulz** [comment]
@dufferzafar Can you test my implementation in  https://github.com/bebraw/pypandoc/pull/115 ?
