### ISSUE TITLE
passing variables to pypandoc?

### ISSUE THREAD

**Issue by colmoneill** [bebraw/pypandoc#111]
I'm writing a small script to take an input file from `argparse` for conversion and publication of .md files to git repos and two mediawikis. Super happy to find this wrapper but I'm running into an issue, and I can't work out if it's my bad python knowledge or pypandoc, here is where I'm at:

```
#!/usr/bin/env python

import argparse
import mwclient
import pypandoc

parser = argparse.ArgumentParser(description='Cross publish your texts to Mediawikis and git repos')
parser.add_argument('-f', '--file', type=argparse.FileType('r'), help='your input text file')
args = parser.parse_args()
print args.file.readlines()

input = args.file.readlines()
print input
output = pypandoc.convert_file(input, 'mediawiki')
print output
```
but when I run it, I get this response:
```
Traceback (most recent call last):
  File "crosspublish.py", line 14, in <module>
    output = pypandoc.convert_file(input, 'mediawiki')
  File "/usr/local/lib/python2.7/dist-packages/pypandoc/__init__.py", line 137, in convert_file
    raise RuntimeError("source_file is not a valid path")
RuntimeError: source_file is not a valid path
```
For which I can not fine a solution. Is it not possible to pass variables to pypandoc?

Many many thanks, and all the best.

**Comment by janschulz** [comment]
Covert_file expects a filename as input, and currently you pass in the filecontent. You either change your code to get a filename (an opened file like the parser currently returns does not work) from your parser or read in the file like now and use convert_text on your input.

**Comment by colmoneill** [comment]
Hey, thanks that did it, thanks for your help and time!
Cheers!
