### ISSUE TITLE
Pandoc 1.18 compatibility

### ISSUE THREAD

**Issue by TomAugspurger** [bebraw/pypandoc#112]
Looks like the first change [here](http://pandoc.org/releases.html) broke some things for pypandoc.

Without looking at anything other than the error message, it looks like before you were parsing the output of `pandoc --version` to get the list of input and output formats. Now you should just be able to parse `pandoc --list-input-formats`, likewise for output.

**Comment by bebraw** [comment]
Yeah, PR would be welcome. Ideally it should try to parse from `--list-input-formats` and if that fails, from `--version`.

**Comment by janschulz** [comment]
Please see https://github.com/bebraw/pypandoc/pull/113 for a fix
