### ISSUE TITLE
Enable appveyor on PRs

### ISSUE THREAD

**Issue by janschulz** [bebraw/pypandoc#118]
@bebraw It seems that you have to enable that in the github repo: http://help.appveyor.com/discussions/questions/203-auto-run-tests-on-pull-requests#comment_33212404 Unfortunately, I don't have access to this config options.could you enable this?

FYI: appveyor currently runs under my account (which seems to ok: in contrast to travis, the appveyor build is not paired with the github repo, but with a person having access to the repo -> on appveyor, you can have multiple persons running builds for the same repo) with my pypi upload credentials. 

Travis also runs with my pypi upload credentials

**Comment by bebraw** [comment]
I enabled AppVeyor on the project.

Would it be easier if we moved pypandoc behind your account? That would feel justified. I don't mind remaining as a collaborator. 👍
