### ISSUE TITLE
Test failure with texlive 2016.43757

### ISSUE THREAD

**Issue by felixonmars** [bebraw/pypandoc#132]
```
======================================================================
ERROR: test_pdf_conversion (tests.TestPypandoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-pypandoc/src/pypandoc-1.4/tests.py", line 322, in test_pdf_conversion
    ret = pypandoc.convert_text('#some title\n', to='pdf', format='md', outputfile=file_name)
  File "/build/python-pypandoc/src/pypandoc-1.4/pypandoc/__init__.py", line 103, in convert_text
    outputfile=outputfile, filters=filters)
  File "/build/python-pypandoc/src/pypandoc-1.4/pypandoc/__init__.py", line 325, in _convert_input
    'Pandoc died with exitcode "%s" during conversion: %s' % (p.returncode, stderr)
RuntimeError: Pandoc died with exitcode "43" during conversion: b"!pdfTeX error: pdflatex (file ec-lmr10): Font ec-lmr10 at 600 not found\n ==> Fatal error occurred, no output PDF file produced!\n\nkpathsea: Running mktexpk --mfmode / --bdpi 600 --mag 1+0/600 --dpi 600 ec-lmr10\nmktexpk: don't know how to create bitmap font for ec-lmr10.\nmktexpk: perhaps ec-lmr10 is missing from the map file.\nkpathsea: Appending font creation commands to missfont.log.\n\npandoc: Error producing PDF\n"

----------------------------------------------------------------------
Ran 24 tests in 2.828s

FAILED (errors=1)
```

**Comment by janschulz** [comment]
@felixonmars Can you give a bit more background (OS + what packages)? I've actually no clue how to reproduce. I've only access to a debian system. 

Somehow the error message indicates that a certain font is missing.

**Comment by felixonmars** [comment]
It is on latest Arch Linux with texlive-core 2016.43757-1 installed.

The following file is present:
/usr/share/texmf-dist/fonts/tfm/public/lm/ec-lmr10.tfm

**Comment by adoussot** [comment]
I have the same error using pandoc cli (not pypandoc) on manjaro Arch Linux with texlive-latexextra 2016.43768-1 installed

**Comment by janschulz** [comment]
Sorry, I've no real clue what is happening here. The tests do not much, just some markdown headlines / paragraphs to other formats. So my guess is, that pandoc seems to require a certain font/latex package which seems to be not in Arch linux texlive package/dependency chain.

My guess is that, that it would also happen with a simple `echo "# Headline"  | pandoc ...`. If that's so, it would be nice if you could either escalate this to the texlive maintainer in you distribution or investigate whether we should adjust out install instruction for Arch Linux to make the experience for you better.

**Comment by felixonmars** [comment]
Thanks for the info. It does look like a packaging issue for me. For example, it always works if I simply reinstall the texlive-core package (but not after a fresh installation in a clean chroot).

**Comment by jkseppan** [comment]
A similar problem in Matplotlib can be worked around by running `updmap --cnffile /etc/texmf/web2c/updmap.cfg -sys` as root. This helps when the font is installed but is missing from the `pdftex.map` file, which seems to happen on Arch Linux for some reason.

**Comment by jankatins** [comment]
@felixonmars This looks liek a arch problem. If you think pypandoc can do anything about this problem, please speak up and reopen the issue.
