### ISSUE TITLE
pandoc_download leaves installer at working directory

### ISSUE THREAD

**Issue by sameersingh7** [bebraw/pypandoc#134]
The code does not remove the file from working directory.

So if code is run by Travis CI, the installer may get committed as well in the repository.
It should make sure that file is removed from the working directory after the run.

**Comment by sameersingh7** [comment]
I'd like to work on this.

**Comment by janschulz** [comment]
Do you have an example where this is happening?

The current sdist on pypi is fine: https://pypi.python.org/pypi/pypandoc

**Comment by sameersingh7** [comment]
"Now, pypandoc leaves the installer in the current working directory after download, which is fine locally, but creates a problem when run on remote systems like Travis. The installer could get committed accidently to the repository. To solve this, I had to take a look at source code for pypandoc and call an internal method, which pypandoc basically uses to set the name of the installer. I use that method to find out the name of the file and then delete it after installation is over."

http://blog.fossasia.org/generating-a-documentation-site-from-markup-documents-with-sphinx-and-pandoc/

**Comment by janschulz** [comment]
#135 is merged, so closing... I need to do a release...
