### ISSUE TITLE
Feature Request : Quiet mode for download_pandoc

### ISSUE THREAD

**Issue by pri22296** [bebraw/pypandoc#140]
It would be nice, If `download_pandoc` provides a way to control whether logs are printed or not.

**Comment by janschulz** [comment]
Hi, what is you usecase here?

**Comment by janschulz** [comment]
This could be used: http://stackoverflow.com/a/12503246/1380673

**Comment by pri22296** [comment]
@janschulz Thanks for the response. Yeah that should work. So should this issue be closed?

**Comment by pri22296** [comment]
@janschulz I needed to suppress the output of download_pandoc as i was trying to implement a quiet mode
for my own script.

**Comment by janschulz** [comment]
So, only the prints? My guess is that teh extraction will also output something.

Anyway: I wouldn't mind a "quiet" keyword, if someone sends a PR.
