### ISSUE TITLE
py 3.6 truncates output rst

### ISSUE THREAD

**Issue by maphew** [bebraw/pypandoc#147]
I'm not sure if this is a setuptools or pypandoc issue:

`python setup.py bdist_wheel` on this [setup.py][0] running from `Python 3.6.2 :: Anaconda, Inc.` on Windows 7 only the 1st line is captured to `{wheel}\{package}.dist-info\DESCRIPTION.rst`. On python 2.7.5 and 2.7.14 the full file is captured.

Pypandoc excerpt from the script:
~~~
try:
    from pypandoc import convert
    def read_md(f): return convert(f, 'rst')

except ImportError:
    print("warning: pypandoc module not found, "
          "could not convert Markdown to RST")

long_description = read_md('README.md')
~~~

When run in interactive console the whole file is in the `long_description` variable
~~~
(C:\apps\Miniconda3) D:\github\leo-editor>python
Python 3.6.2 |Anaconda, Inc.| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bi
t (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pypandoc import convert
>>> def read_md(f): return convert(f, 'rst')
...
>>> long_description = read_md('README.md')
>>> long_description
'Leo 5.6 September 25, 2017\r\n\r\n`Leo <http://leoeditor.com/>`__ 5.6 is now av
...snip 15 console output lines...
\r\n-  `A web page that displays .leo\r\n   files <http://leoeditor.com/load-leo
.html>`__\r\n-  `More links <http://leoeditor.com/leoLinks.html>`__\r\n'
~~~

[0]: https://github.com/leo-editor/leo-editor/blob/94ebac1f2510330a810f180051d59eab8ddf2aab/setup.py

**Comment by maphew** [comment]
Replicated on 2 machines, though both running Win7. Here's the output of each (.txt added so GitHub allows upload):

* [py36_DESCRIPTION.rst.txt](https://github.com/bebraw/pypandoc/files/1447848/py36_DESCRIPTION.rst.txt)
* [py27_DESCRIPTION.rst.txt](https://github.com/bebraw/pypandoc/files/1447849/py27_DESCRIPTION.rst.txt)

**Comment by jankatins** [comment]
This looks more like  setuptools/wheel problem than a pypandoc one? @machow did you find a workaround?

**Comment by jankatins** [comment]
Replaced the conversion with plan MD as pypi now supports it.
