### ISSUE TITLE
Q: How to create a pypandoc reader?

### ISSUE THREAD

**Issue by alecthegeek** [bebraw/pypandoc#151]
I have a loop that generates markdown for conversion by Pandoc.

Is there some way to create a reader so that I can keep writing to Pandoc until I exhaust my input data?

I wanted to save appending to a (possibly big) string -- that can be inefficient.

Thanks

**Comment by jankatins** [comment]
Currently this is not possible. It might be possible, but it would basically mean that we have to refactor the whole thing.

It's much easier to use https://docs.python.org/2/library/stringio.html for this: simply write to the stringio writer and get the resulting string in the end and pass it to pypandoc. Is that enough for your case?

**Comment by alecthegeek** [comment]
thanks

**Comment by alecthegeek** [comment]
Or for Python3 https://docs.python.org/3/library/io.html#io.StringIO
