### ISSUE TITLE
Idea: Create wheels bundled with pandoc

### ISSUE THREAD

**Issue by msabramo** [bebraw/pypandoc#16]
I think the one tricky thing about this module is that it relies on having pandoc installed and that's not Python. 

I wonder if you can create wheels on OS X and Linux that bundle a pre-built pandoc binary. You'd have to check with John MacFarlane to see if he's ok with this, but I think it will meet the license (GPL) as long as you include a notice with a link to the source code. 

I mention OS X and Windows and not Linux because PyPI won't let you upload binary wheels for Linux, because it's very hard to build one that works reliably across different Linux versions.

**Comment by bebraw** [comment]
What do you want to do with this issue?

**Comment by msabramo** [comment]
@bebraw: Take a look at https://github.com/bebraw/pypandoc/pull/37 -- hopefully you have a Mac to test it on.

Not sure how you do the same on Linux, but I suspect that it's possible.

**Comment by JanSchulz** [comment]
rstudio also bundles pandoc

**Comment by JanSchulz** [comment]
the used builds for rstudio are here: https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.13.1.zip (and probably other versions, as they are used in in travis builds: https://github.com/travis-ci/travis-build/pull/386/files#diff-5b7e1aa01f1c6f058df6e0b9e2486c62R370). They include linux, mac and windows versions...

Not sure if that is "nice", but:

```
if build_type == wheel:
   wget RStudio_pandoc.zip
   untip the right one into a special dir
   include the files in the wheel build
```

And in the code then add something, which takes into account the filepath to that dir...

**Comment by pombreda** [comment]
:+1:  for vendoring pandoc binaries. I actually have code for a soon to be released library that does just that.

**Comment by JanSchulz** [comment]
So, should this happen on all wheel builds? I'm willing to give this a try... It seems that it needs a special treatment for all supported archs as rstudio doesn't ship newer versions than 1.13.

On windows:
* create `%temp_dir%` + `%temp_dir%\pandoc`
* use request or whatever to downlaod the latest pandoc version from pandocs download page to %temp_dir%
* `msiexec /a %temp_dir%\pandoc-1.15.0.6-windows.msi /qb TARGETDIR=%temp_dir%\pandoc
* copy pandoc and pandoc-citeproc to a the right dir in the source (where is that? in other repos I would add `pypandoc/{__init__.py,bin/} and copy to bin, but pypadoc is structured without a package dir)
* include it in the wheel build...
* make the bin searcher aware of that dir

Most of the stuff above would be universal, only the package URL and the extraction command needs to be adjusted for different platforms... 

Oh, and pandoc only adds Linux AMD64, OSX and windows packages, so the rest is out of luck...

**Comment by bebraw** [comment]
@msabramo Any thoughts?

**Comment by JanSchulz** [comment]
Ok, the other way (and probably much easier): include it in the source repo ala https://github.com/bebraw/pypandoc/pull/37

**Comment by JanSchulz** [comment]
See #73 for an idea how to build wheels with pandoc binaries included.
