### ISSUE TITLE
How hard would it be to support pandoc-crossref?

### ISSUE THREAD

**Issue by wfspotz** [bebraw/pypandoc#162]
Pypandoc already provides the `pandoc-citeproc` filter automatically, so how hard would it be to support the `pandoc-crossref` filter in the same way?

**Comment by jankatins** [comment]
citeref is included with pandoc, crossref seems to be another package. So if you get it installed in the OS, you can simply pass it in as a filter.

`convert_text(...,filters=['pandoc-citeproc'])`
