### ISSUE TITLE
empty package with pip installation version 1.4

### ISSUE THREAD

**Issue by dtrckd** [bebraw/pypandoc#165]
Hi,
When installing pypandoc with pip (python 3.6), the current version (1.4) is installed but the package seems to be empty and no function can be called.

As a workaround, I reinstall the previous version with `pip install  pypandoc==1.3.3`  which makes the module usable.

**Comment by jankatins** [comment]
The pypi files has everything in there as far as I understand these files. 

I'm about to do a release, lets see if that still has the problem. If not, please reopen.
