### ISSUE TITLE
Add support for setting folder where pypandoc downloads installation files to

### ISSUE THREAD

**Issue by NicklasTegner** [bebraw/pypandoc#167]
Hi.
Would it be posible to be able to specify the path to where pypandoc downloads installation packages for pandoc.
Like where you can set "download_pandoc(targetfolder="path/to/custom/pandoc/folder")"
Installation pages are the files like "pandoc-2.4-windows-x86_64.msi", "pandoc-2.4-windows-x86_64.pkg" and such.

### Suggestion:
Extend the pypandoc.download_pandoc function to include an argument for setting the installer download folder.
Something like: download_pandoc(targetfolder/"Here/pandoc/gets/installed", installation_file_cash="here/the/temporary/installation/files/gets/downloaded/to")
And set it so the new parameter defaults to the current working dir (like it does now), if a custom path aren't provided.

### Why:
It cause problems for windows users (with User account control) and Mac Os users, if the program that used pypandoc (that tries to download pandoc through pypandoc) are placed in a permission restricted folder (f.x. the C:\Program Files\) or in /Applications on mac.

**Comment by ecederstrand** [comment]
Isn't this what the `targetfolder` argument does? See https://github.com/bebraw/pypandoc/blob/master/pypandoc/pandoc_download.py#L152

**Comment by NicklasMCHD** [comment]
@ecederstrand 
this is not what targetfolder does, from the file itself:
* targetfolder: directory, where the binaries should be installed.

What that does, is set the path, where pandoc gets installed. What I'm asking for, is an option to set where the pandoc installers (ie pandoc-x.x.msi and the same for mac) gets downloaded to, before getting installed.

**Comment by abarrafo** [comment]
I fixed this in a branch,  but it seems this repo is locked down without instruction in the `Contribution` block on how to proceed. I am unable to push my branch and create a pull request. 

I am running pypandoc in an AWS Lambda function that only permits file write access into the `/tmp` path requiring this implementation.

**Comment by abarrafo** [comment]
> I fixed this in a branch, but it seems this repo is locked down without instruction in the `Contribution` block on how to proceed. I am unable to push my branch and create a pull request.
> 
> I am running pypandoc in an AWS Lambda function that only permits file write access into the `/tmp` path requiring this implementation.

Ok, I was able to fork https://github.com/abarrafo/pypandoc it and then create a PR. Looks like the project has some broken CI/CD stuff that needs attending to proceed with a merge here.
