### ISSUE TITLE
Make a release with latest changes

### ISSUE THREAD

**Issue by Peque** [bebraw/pypandoc#170]
Interested in https://github.com/bebraw/pypandoc/issues/146 specially.

@jankatins friendly ping. :innocent:

**Comment by sternenseemann** [comment]
Would be great to see this, as the last released version doesn't work with pandoc2 which currently [prevents NixOS from providing a working version of pypandoc](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/pypandoc/default.nix#L31).

**Comment by jankatins** [comment]
1.5 is on pypi. Sorry for the long wait...
