### ISSUE TITLE
Wrapper around pandoc should also be GPL

### ISSUE THREAD

**Issue by kiwi0fruit** [bebraw/pypandoc#171]
There are no exceptions about that in Pandoc license and the way of linking doesn't matter (though the way of linking would have mattered if Pandoc was LGPL).

**Comment by waschk** [comment]
Pypandoc isn't linked at all with Pandoc. It is a separate process.

> By contrast, pipes, sockets and command-line arguments are communication mechanisms normally used between two separate programs. So when they are used for communication, the modules normally are separate programs.
https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html#MereAggregation

**Comment by kiwi0fruit** [comment]
Thanks! I'll close it then.

**Comment by kiwi0fruit** [comment]
But at the same time I'm not completely convinced:

> What constitutes combining two parts into one program? This is a legal question, which ultimately judges will decide. We believe that a proper criterion depends both on the mechanism of communication (exec, pipes, rpc, function calls within a shared address space, etc.) and the semantics of the communication (what kinds of information are interchanged).

> But if the semantics of the communication are intimate enough, exchanging complex internal data structures, that too could be a basis to consider the two parts as combined into a larger program. 

I guess getting Pandoc's AST may be considered as "internal data structures".

**Comment by kiwi0fruit** [comment]
I doubt that it can be resolved without @jgm stating his opinion.

**Comment by jgm** [comment]
The `pandoc-types` module that defines the AST is dual licensed, if that helps.

**Comment by kiwi0fruit** [comment]
Thanks a lot! That's almost certainly helps.
