### ISSUE TITLE
Getting stderr of pandoc filter

### ISSUE THREAD

**Issue by fralau** [bebraw/pypandoc#172]
For debug reasons, it would be useful to get the stderr of filters run by pandoc (in panflute, there is a `debug` function for writing into stderr).
The `convert_file` or `convert_text` functions return the stdout, which is fine. What about the stderr? Would there be any way to catch it?

**Comment by jankatins** [comment]
Yes. We currently return stderr when the resturncode is non-zero: 

```py
    # check that pandoc returned successfully
    if p.returncode != 0:
        raise RuntimeError(
            'Pandoc died with exitcode "%s" during conversion: %s' % (p.returncode, stderr)
        )
```

Is that enough for your usecase. Please reopen if you have another requriement
