### ISSUE TITLE
installation fails on linux

### ISSUE THREAD

**Issue by miweru** [bebraw/pypandoc#174]
when unpacking the deb folder of pandoc in the temp file, the following error occurs:
`subprocess.CalledProcessError: Command '['tar', 'xzf', 'data.tar.gz']' returned non-zero exit status 2.
`
the newest pandoc file unpacks to a file data.tar.xz and "data.tar.gz" does not exist anymore.
When i change line 86 in "pandoc_download.py" from
`cmd = ["tar", "xzf", "data.tar.gz"]`
 to
`cmd = ["tar", "xJf", "data.tar.xz"]`
it works.

**Comment by richardbrinkman** [comment]
I see that the master branch has fixed the issue in commit 1515c60faf397248120507ee3519aa5fb4d1ea27. Is it possible to make a new release and upload it to PyPi? The latest release is almost 3 years old already.

**Comment by mortenvp** [comment]
Would be great with a pypi release :) We're also affected by this issue.

**Comment by jankatins** [comment]
Fix has been merged.

Will tag a release when windows works again -> looks good so far...
