### ISSUE TITLE
How to get variables from YAML metadata of a Markdown file

### ISSUE THREAD

**Issue by ketozhang** [bebraw/pypandoc#175]
Let's say we have some YAML header in a markdown file like so

```md
---
title: TITLE
---

Some content
```
Is it possible with pypandoc to extract the "title" variable using pypandoc?

EDIT: There's two ideas I have in mind. One to parse YAML within "---" delimiters. The other begin [python-frontmatter](http://python-frontmatter.readthedocs.io).

**Comment by jankatins** [comment]
This is basically pandoc territory, not pypandoc. It would be better to ask there.

**Comment by ketozhang** [comment]
Well got it, thanks.

From the ability of pypandoc able to get a string from the converter it seems like it can do more. Otherwise the most simplest wrapper would just be a pythonic way to call pypandoc.

**Comment by jankatins** [comment]
We currently do not touch the to be converted file in any way, so that would be new for us. Pandoc itself does something with the metadata: https://pandoc.org/MANUAL.html#extension-yaml_metadata_block
