### ISSUE TITLE
Problem When Transcribing Greek HTML Letters to LaTex

### ISSUE THREAD

**Issue by totyped** [bebraw/pypandoc#178]
Hi ! 

I have described my problem[ here](https://stackoverflow.com/questions/55642183/problem-when-transcribing-greek-html-letters-to-latex/55642483#55642483) and I would be very pleased,  if anyone could help me fix this problem !

**Comment by jankatins** [comment]
This is a pandoc problem, we only use pandoc so cannot do anything here :-(
