### ISSUE TITLE
convert large html to docx

### ISSUE THREAD

**Issue by davendw49** [bebraw/pypandoc#191]
i try to convert a 200MB Html file with many images which are embedding in word in the form of  base64 code, but it works on linux without any errors but it has an exitcode 251 on windows with 
![error](https://user-images.githubusercontent.com/32675226/81134347-08402580-8f87-11ea-835d-09ce6b25e40f.png)
my code is 
![mycode](https://user-images.githubusercontent.com/32675226/81134446-5ead6400-8f87-11ea-88fa-78e38e145a56.png)
if it has a solution that would be great

**Comment by jankatins** [comment]
Sorry, this is a pandoc error and we cannot do anything about that. Please report your error upstream. 


My guess is that they will tell you to get more RAM in this case, 'MEM_COMMIT failed' looks liek a "out of memory" situation :-/
