### ISSUE TITLE
Coordinate a release - 0.90

### ISSUE THREAD

**Issue by bebraw** [bebraw/pypandoc#30]
* [ ] Add @msabramo's contributions to README
* [ ] Figure out what to with #9. @msabramo, I would appreciate your input here.

Am I missing something? I can't think of any other tasks.

**Comment by msabramo** [comment]
I like the idea of renaming `services.py` and putting it in an `examples` folder. I think I would remove the Django File and just have it return the temporary file directly or a string. Dependency injection might be overkill.

**Comment by msabramo** [comment]
I have an idea but I think it can wait until after 0.90. 

Idea is to add option to use and/or fallback to http://docverter.com instead of local pandoc. This could be huge, because then you could possibly use pypandoc without having pandoc installed.

**Comment by bebraw** [comment]
> I like the idea of renaming services.py and putting it in an examples folder. I think I would remove the Django File and just have it return the temporary file directly or a string. Dependency injection might be overkill.

Ok, let's go with that then. I'll do the change for 0.90.
