### ISSUE TITLE
Add option to use Docverter

### ISSUE THREAD

**Issue by msabramo** [bebraw/pypandoc#34]
I have an idea but I think it can wait until after 0.90. 

Idea is to add option to use and/or fallback to http://docverter.com instead of local pandoc. This could be huge, because then you could possibly use pypandoc without having pandoc installed.

**Comment by bebraw** [comment]
I wonder if it would make sense to set up a sibling project with the same API for that (`pydocverter` or something). Then you could do things like:

```python
try:
    import pypandoc as converter
except ImportError:
    import docverter as converter

...

converter.convert(...)
```

Or alternatively we can add some extra parameter to `convert` for that.

**Comment by msabramo** [comment]
Interesting. I was thinking of it built into pypandoc, but this is an interesting idea. I'll have to let that float around in my head for a bit.

**Comment by msabramo** [comment]
https://gist.github.com/yoavram/4356539
https://gist.github.com/wcaleb/5478130

**Comment by msabramo** [comment]
I'm thinking a separate module for docverter makes sense. Then each one will be simpler. Maybe pypandoc could use the new module as an extra.

**Comment by msabramo** [comment]
I have some code locally for a pydocverter module. I'll publish a bit later.

**Comment by bebraw** [comment]
Ok, if you want we can add a mention about this sort of usage to the readme so people are aware of it. I can link to your module there.

**Comment by msabramo** [comment]
https://github.com/msabramo/pydocverter

**Comment by bebraw** [comment]
Nice! Let me know once it's at PyPI and I'll add a small example and mention to README (or you can do a PR if you want something specific).

**Comment by msabramo** [comment]
Just uploaded it to PyPI: https://pypi.python.org/pypi/pydocverter

**Comment by msabramo** [comment]
See https://github.com/bebraw/pypandoc/pull/35

**Comment by bebraw** [comment]
Merged. I did a minor release (0.9.1) that contains the readme update. Thanks!
