### ISSUE TITLE
Fix Linux tests of Travis

### ISSUE THREAD

**Issue by bebraw** [bebraw/pypandoc#42]
@msabramo Any idea what would be a good way to resolve this? Now we're getting nasty failures. Example of a failure: https://travis-ci.org/bebraw/pypandoc/jobs/52296424 . Pandoc is giving `pandoc: Unknown reader: markdown+strikeout`.

Can we benefit from http://docs.travis-ci.com/user/build-configuration/#Installing-Packages-Using-apt ?

**Comment by JanSchulz** [comment]
Oups, this is now handled in #45 and fixed in PR #46

**Comment by bebraw** [comment]
Yeah, safe to close.

I'll have a look at those failing Pyflakes cases.

**Comment by msabramo** [comment]
Awesome! I would've suggested downloading a new pandoc and @JanSchulz did it, which is awesome!
