### ISSUE TITLE
can't convert to docx

### ISSUE THREAD

**Issue by JanSchulz** [bebraw/pypandoc#43]
Using this to convert to docx does not work:

```
pandoc: Cannot write docx output to stdout.
Specify an output file using the -o option.
```

**Comment by msabramo** [comment]
That's probably because pandoc doesn't support writing docx to stdout:

http://johnmacfarlane.net/pandoc/README.html#using-pandoc

We would need to have pandoc write output to a temp file instead of reading its stdout. Shouldn't be too hard. I'm sure @bebraw would appreciate a pull request.

**Comment by bebraw** [comment]
Good catch @msabramo!

Yeah, a PR would be very welcome. :)

**Comment by JanSchulz** [comment]
One problem I encountered is that a tempfile approach needs to either return nothing/ the filename or indicate what the encoding is (reading in a docx needs to be bytes not utf8 encoded string :-(

RStudio/rmarkdown/knitr handles that by only using files (e.g. it defines a proper output filename and uses `-o outfile.xxx` for all handling

**Comment by bebraw** [comment]
@JanSchulz What if you gave the output target to `pypandoc` as a parameter (ie. `output="somepath/my.docx"`)? Then it could be passed to pandoc. Would that help?

**Comment by JanSchulz** [comment]
So the logic would be

* if output: append "-o output" to comamndline and discard stdout and don't return anything
* if to in ["docx",...] and no outputfile: raise Exception

Sounds fine with me, I can do such a PR

**Comment by bebraw** [comment]
@JanSchulz Sounds great! Besides that logic I expect that you

* Document the functionality at README
* Add yourself to contributors at README
* Write test cases for the logic

This will save both of our time in the review phase.

Thanks! :)

**Comment by JanSchulz** [comment]
ok, on it.

**Comment by JanSchulz** [comment]
@bebraw done, see #44

**Comment by bebraw** [comment]
Merged so closing.
