### ISSUE TITLE
use newer pandoc

### ISSUE THREAD

**Issue by JanSchulz** [bebraw/pypandoc#45]
See here for the problem: https://github.com/bebraw/pypandoc/pull/44#issuecomment-77880052
-> travis only installs 0.9, but pandoc > 0.10 is needed to support extensions

There are several possible ideas to fix this (apart from "build pandoc from source)
* use IPythons version (see their travis config: https://github.com/ipython/ipython/blob/master/.travis.yml -> this will break if IPYthon removes this version, but only 19MB download
* use the one from RStudio (travis uses that in their r environment): https://github.com/travis-ci/travis-build/pull/386/files#diff-5b7e1aa01f1c6f058df6e0b9e2486c62R370 -> probably stable, but is a 100+MB download
* use a language=r travis config, which has a newer pandoc version and install python via conda :-)

**Comment by bebraw** [comment]
> use a language=r travis config, which has a newer pandoc version and install python via conda :-)

I guess the gotcha with this is that it would make it difficult to test against multiple versions of Python.

The IPython solution seems most promising!

@msabramo Again, your input is valued. :)

**Comment by JanSchulz** [comment]
I've a PR incoming which uses the IPython version.

Re R language: you would have to do all by hand, but I think it can work :-)

**Comment by JanSchulz** [comment]
Yay, it worked :-) https://travis-ci.org/bebraw/pypandoc/jobs/53681285
