### ISSUE TITLE
pandoc-citeproc not recognized as an option

### ISSUE THREAD

**Issue by xysmas** [bebraw/pypandoc#47]
I have a small script that uses pypandoc to put a file's current YAML frontmatter into the pandoc'ed output file (for jekyll). 

The file works great until I attempt to add in a filter option:
```{.python}
pdoc_args = ['--mathjax',
                     '--smart',
                     '--filter pandoc-citeproc'
                     ]
```
produces:
```
$ ./pyconverter.py yaml_frontmatter.md 
Converting yaml_frontmatter.md
pandoc: unrecognized option `--filter pandoc-citeproc'

```

fwiw, i have pandoc-citeproc installed and it works fine with the same options from the command line:

```
$ pandoc --mathjax --smart --filter pandoc-citeproc yaml_frontmatter.md 
```

Produces:
```{.html}
<p class="notice-info">
<strong>Content Warning:</strong> Machine Learning, Python
</p>
<h2 id="section">Section</h2>
<p>See <span class="citation">(see Fenner 2012)</span></p>
<p>Inline Math: <span class="math">\(\sum_{i}^{n_1}\)</span></p>
<p>display math:</p>
<p>[ \begin{align} x = 1 y = 2 ]</p>
<pre class="sourceCode python"><code class="sourceCode python">testing <span class="kw">for</span> <span class="dt">all</span> in <span class="dt">all</span></code></pre>
<div class="references">
<h1 id="references" class="unnumbered">References</h1>
<p>Fenner, Martin. 2012. “One-Click Science Marketing.” <em>Nature Materials</em> 11 (4). Nature Publishing Group: 261–63. doi:<a href="http://dx.doi.org/10.1038/nmat3283">10.1038/nmat3283</a>.</p>
</div>
```

Thoughts?

**Comment by bebraw** [comment]
What if you had `--filter=pandoc-citeproc` instead of `--filter pandoc-citeproc`? I have a feeling it might need that.

You can see how it constructs the command [here](https://github.com/bebraw/pypandoc/blob/8e6e5e472fbf24e291784aa91919ad679298c510/pypandoc.py#L85).

If the suggested fix works, we could add perhaps an extra check against parameters like this and replace ` ` with `=`.
