### ISSUE TITLE
Add a method to get the pandoc version

### ISSUE THREAD

**Issue by JanSchulz** [bebraw/pypandoc#51]
In knitpy, I have the need to ensure that the used pandoc version is higher than 1.10  (and probably 1.12, similar to ipython nbconvert).

ipython has such a version check: https://github.com/jupyter/jupyter_nbconvert/blob/master/jupyter_nbconvert/utils/pandoc.py#L58, maybe that could be copied to pypandoc?

**Comment by bebraw** [comment]
Yeah, feel free to make a PR for that.

**Comment by JanSchulz** [comment]
done in #53

**Comment by bebraw** [comment]
Merged. I published `0.9.7` with the feature in it.
