### ISSUE TITLE
Adding support for pandoc 1.9.4

### ISSUE THREAD

**Issue by thatcher** [bebraw/pypandoc#52]
I've been successful with pypandoc in several environments including windows and osx.  However in my production environment I'm stuck with Red Hat Enterprise 6 which only supports pandoc 1.9.4 from the official rpm repository.

I'm trying to make use of the great new project knitpy by @JanSchulz for dynamic reports (I have some background in R, but prefer Python though knitr is better for my application that ipython notebooks).

Here are the related threads that get at the gist of the issue before I give you my specific code:

https://github.com/jgm/pandoc/issues/751

If its possible to add some introspection and backward compatible support for calling pandoc 1.9 (documenting what is still not supported given you have to fallback), then that would get me a lot further.

I have the ability to do the coding given the project contributors support but it would go faster if I just a little had direction since pandoc is not something I've worked with.

Here is my ticket for knitpy but this is something I'd see better positioned as a patch to pypandoc.

https://github.com/JanSchulz/knitpy/issues/8

**Comment by bebraw** [comment]
What are the main differences between pandoc 1.9 and newer versions? Is the cli API different somehow?

In any case we can detect for the version and then provide some form of legacy API for 1.9 I think.

**Comment by JanSchulz** [comment]
0.10 includes the big "markup+extension" work, so supporting something below that will likely include either a big warning that the extensions don't work or parsing the inputs themself to get the same output :-/

**Comment by thatcher** [comment]
I was able to get past this via precompiled binaries (normally not an option for me since our production environment is highly controlled).  Thanks for the feedback though and thanks for the project.

**Comment by msabramo** [comment]
I wonder if you could've used Docker to get a working pypandoc with the pandoc bundled in?

https://registry.hub.docker.com/u/msabramo/pypandoc/
