### ISSUE TITLE
Figure out why Travis yields `ValueError: 'Options:' is not in list`

### ISSUE THREAD

**Issue by bebraw** [bebraw/pypandoc#55]
See https://travis-ci.org/bebraw/pypandoc/builds/64269432 .

Why would it fail to find `Options:` in Pandoc output? Any ideas?

cc @msabramo @xysmas

**Comment by bebraw** [comment]
I got a little closer with this by installing Pandoc through a PPA. Still getting an error about `$HOME`. Details: https://travis-ci.org/bebraw/pypandoc/jobs/64681445 .

It looks like `pandoc-citeproc` cannot find that environment variable and Travis documentation explicitly states that you shouldn't depend on the value. I wonder what would be the right way to resolve this.

**Comment by rossant** [comment]
In another project I'm successfully testing pandoc on travis with this:

```
sudo: required
services:
  - docker
addons:
  apt_packages:
    - pandoc
```

shall I try this here?

**Comment by bebraw** [comment]
@rossant Sure! Maybe that's all we need. :+1:

**Comment by bebraw** [comment]
Thanks to @rossant the build is slightly better. We tried disabling certain tests on Travis but for some reason, doing a little check like `if os.environ.get('CI', None):` just won't do the trick. I even tried to set `CI=1` explicitly in Travis config but no dice... Resolving this would give us a semi-decent build.

**Comment by JanSchulz** [comment]
#69 should fix this issue.
