### ISSUE TITLE
Converting from .docx / .odt

### ISSUE THREAD

**Issue by dlukes** [bebraw/pypandoc#57]
Pandoc is also able to take e.g. a `.docx` / `.odt` file and output plain text / markdown / html etc., but pypandoc's current approach of first reading the input file in memory as plain text (`pypandoc.py#147`) and then piping the string to pandoc makes it impossible to take advantage of this (obviously since `.docx` / `.odt` is a compressed archive, not a plain text file).

Maybe this is by design (?); if not, it would be great if pypandoc supported this part of pandoc functionality as well :) (TBH, I don't fully understand why it's necessary to read in the input file and pipe it to pandoc instead of just providing it to the pandoc subprocess call as an argument, but I have only taken a glance at the code and there may be ramifications I'm not aware of...)

Great job otherwise!

**Comment by bebraw** [comment]
I wouldn't mind getting this fixed.

Would it be possible for you to prepare a PR to fix the issue? I don't mind if the implementation gets changed (skips reading to memory initially). The code has grown organically and there are knots like that. 

The test suite is somewhat extensive. Just make sure to add `.docx` / `.odt` case there.

Btw if you have any idea on how to work with Travis, please check out #55. I'm a little stumped with that.

**Comment by dlukes** [comment]
OK, I'll see what I can do and get back to you!

I don't know much about Travis though, unfortunately...

**Comment by bebraw** [comment]
> I don't know much about Travis though, unfortunately...

No probs. :+1:
