### ISSUE TITLE
What is the syntax for converting to pdf?

### ISSUE THREAD

**Issue by gregist** [bebraw/pypandoc#59]
I have tried naively with `output = pypandoc.convert('paper.md', 'pdf')` which won't work.

**Comment by bebraw** [comment]
@gregist Can you provide the native pandoc command that works for the conversion? That will give me a clearer idea of why it doesn't work.

**Comment by gregist** [comment]
@bebraw This line works for me.

`os.system("pandoc " + "paper.md -o paper.pdf --latex-engine=xelatex)`

**Comment by bebraw** [comment]
@gregist So in order to work it requires that `latex-engine` thinger? Is that the only way to get pdf output out of pandoc? If so, we can treat this as a special case or make something more generic and give access to those custom parameters of pandoc.

**Comment by gregist** [comment]
@bebraw Yes, you need LaTex preinstalled in your system.
official document [here](http://pandoc.org/demo/example19/Creating-a-PDF.html).

**Comment by bebraw** [comment]
@gregist Ok, got it. So it defaults to `pdflatex` unless engine is specified. What if I provided you `latexEngine` parameter? Then you could do something like this:

> output = pypandoc.convert('paper.md', 'pdf', latexEngine='xelatex')

Would that work for you?

**Comment by gregist** [comment]
Nope.

```
Traceback (most recent call last):
  File "***\pandocd.py", line 3, in <module>
    output = pypandoc.convert('paper.md', 'pdf', latexEngine='xelatex')
TypeError: convert() got an unexpected keyword argument 'latexEngine'
[Finished in 0.2s with exit code 1]
```

**Comment by bebraw** [comment]
@gregist Yeah, I meant I can implement that parameter there unless someone comes up with a nicer API. :+1:

**Comment by gregist** [comment]
@bebraw Well... that should work.

nice project btw.

**Comment by bebraw** [comment]
@gregist Never mind... Looks like the functionality we need is already there. Try

> output = pypandoc.convert('paper.md', 'pdf', extra_args=['--latex-engine=xelatex'])

I think that should be equivalent to what you wrote earlier.

There's so much functionality I forgot about that. :+1:

**Comment by gregist** [comment]
```
Traceback (most recent call last):
  File "***\try.py", line 3, in <module>
    output = pypandoc.convert('paper.md', 'pdf', extra_args=['--latex-engine=xelatex'])
  File "C:\Python27\lib\site-packages\pypandoc.py", line 94, in convert
    outputfile=outputfile, filters=filters)
  File "C:\Python27\lib\site-packages\pypandoc.py", line 135, in _convert
    outputfile=outputfile, filters=filters)
  File "C:\Python27\lib\site-packages\pypandoc.py", line 208, in _process_file
    'Pandoc died with exitcode "%s" during conversation: %s' % (p.returncode, stderr)
RuntimeError: Pandoc died with exitcode "9" during conversation: pandoc: Unknown writer: pdf

To create a pdf with pandoc, use the latex or beamer writer and specify

an output file with .pdf extension (pandoc -t latex -o filename.pdf).


[Finished in 0.2s with exit code 1]
```

**Comment by bebraw** [comment]
@gregist I made it discard `--to` parameter for pdf and published `0.9.9`. That should fix it.

**Comment by gregist** [comment]
@bebraw COOL. It works!

pypandoc won't recogonize some formatting argument though. e.g.
`output = pypandoc.convert('paper.md', 'pdf', outputfile='paper.pdf', extra_args=['-V geometry:margin=1.5cm'])`

No error coughed. Just that the formatting isn't right.

**Comment by bebraw** [comment]
@gregist If you look at the current implementation `extra_args` are just passed to `subprocess.Popen`. Can you try against that or `os.system` so we get something to compare with again?

**Comment by gregist** [comment]
@bebraw 

the code:
```
import pypandoc
import os
output = pypandoc.convert('paper.md', 'pdf', outputfile='paper.pdf', extra_args=['-V geometry:margin=1.5cm'])
os.system("pandoc "+'paper.md -o paper2.pdf -V geometry:margin=1.5cm')
```
the output:
* pypandoc
![](http://i.imgur.com/vgPrrSq.png)
* os.system
![](http://i.imgur.com/JIl8Mrx.png)

I don't know how to implement with `subprocess.Popen`, or you can pass me the code and I'd be happy to test it for you.

**Comment by bebraw** [comment]
That's enough to debug. Thanks. I'll look into it.

**Comment by bebraw** [comment]
@gregist Looks like it's very strict about parameters. The following works for me:

> output = pypandoc.convert('demo.md', 'pdf', outputfile='paper.pdf', extra_args=['-V', 'geometry:margin=1.5cm'])

I'm not sure if this a bug in pypandoc itself or how to even start to fix it since it's so fundamental. There's probably a good reason why it works this way, though.

**Comment by gregist** [comment]
@bebraw 
>The following works for me:

can confirm. cheers!

Yes it's a little weird why seperated quotes work while otherwise does not. Maybe we should 'feature' this bug by including it in the documentations.

**Comment by bebraw** [comment]
Sure. I'll add a brief note about it.
