### ISSUE TITLE
Please add license text to the released tarball

### ISSUE THREAD

**Issue by valholl** [bebraw/pypandoc#60]
I've noticed that the tarball released on pypi is missing the LICENSE file, and while there are references to the MIT license, the only way to know the actual licensing terms is from the git repo.

Also, the code taken from IPython py3compat.py and encoding.py is marked as under the Modified BSD License, but the actual text of that license (plus copyright notice) is not repeated anywhere in the package (as requested by the license: "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."). IANAL, but I believe that adding the text of the Modified BSD to LICENSE (including the copyright notice and specifying the parts to which it applies) should be enought.

Thanks in advance

**Comment by bebraw** [comment]
Is it enough if I add `LICENSE` to `MANIFEST.in`? I don't mind accepting a PR for this. As far as I'm concerned the source is under MIT (a nominal thing really).

I barely develop Python these days so I'm pretty out of the loop with these things. :+1:
