### ISSUE TITLE
Specifying path to pandoc

### ISSUE THREAD

**Issue by wcaleb** [bebraw/pypandoc#72]
Is there some way to specify the path to pandoc within a script? I am importing pypandoc into a Flask app that runs on an Apache server, and since the server runs as a special Apache user, the app can't seem to find pandoc even though it's installed in my own user path. I know [pyandoc](https://github.com/kennethreitz/pyandoc) had a way around this with a variable for the pandoc path, but can't tell if there's a way to manage that here.

**Comment by JanSchulz** [comment]
As far as I know there isn't. Pandoc is expected to be on the PATH, so if you have any way to change that for your script it should be fine...

Having a way to specify the pandoc path would be a nice first strep to include the pandoc binary in a wheel...

**Comment by bebraw** [comment]
PR is welcome. :+1:

**Comment by JanSchulz** [comment]
See #73 for a PR implementing this

**Comment by wcaleb** [comment]
Thanks for working on this!

**Comment by bebraw** [comment]
@wcaleb Just to clarify, it should work based on `PYPANDOC_PANDOC` now. Set that through env.

**Comment by gwgundersen** [comment]
I have an issue that is, I think, related to this. I have pandoc and pypandoc both installed, and everything works from the REPL. But when I try to execute pypandoc from my Flask application, I get a "No pandoc was found" error. How is `PYPANDOC_PANDOC` related to fixing this issue? Thanks.

**Comment by gwgundersen** [comment]
For anyone else who finds this question searching for a solution, just set the environment variable at the Flask instance startup, e.g.:

```
# __init__.py

import os
os.environ.setdefault('PYPANDOC_PANDOC', '/usr/local/bin/pandoc')
```

**Comment by bebraw** [comment]
@gwgundersen Maybe that's worth adding to the README?

**Comment by gwgundersen** [comment]
Okay, see PR #99 for my attempt at explaining this.
