### ISSUE TITLE
Enable travis builds on push?

### ISSUE THREAD

**Issue by JanSchulz** [bebraw/pypandoc#75]
It seems that pushes to master will not result in an travis run.

@bebraw Would you mind going to https://travis-ci.org/bebraw/pypandoc/settings and enable `Build pushes`?

I would like to make a release so that I can supply wheels for macosx and windows (it seems that you can't upload wheels for linux) and build the conda packages for all three platforms.

My release checklist is
* make it (travis) green
* bump version and tag as 'v1.1.1'
* push tags and commit to master

Anything I missed?

**Comment by bebraw** [comment]
It should be enabled. I'm not entirely sure why it wouldn't build on a push. See below:

![screenshot 2015-10-22 21 41 42](https://cloud.githubusercontent.com/assets/166921/10674837/c1bab1d0-7905-11e5-8dbe-a3499f455866.png)

If you want, I can try to force a build.

**Comment by JanSchulz** [comment]
ok, my mistake. Seems that I should look at https://travis-ci.org/bebraw/pypandoc and not the small dot next to the the commit Ids. 

Ok, lets do a release then...

**Comment by bebraw** [comment]
@JanSchulz Do you want to do the honors? Just to make sure everything works fine. :)

**Comment by JanSchulz** [comment]
I hope I got it all: The above missed a `python setup.py sdist; twine upload dist\pypandoc*1.1.1*.zip`.

Can you have a look if I messed something up?

**Comment by bebraw** [comment]
Given tests pass I would say we're quite safe. Go ahead. I'm sure we'll hear if we managed to break something. :)

**Comment by JanSchulz** [comment]
Hm, ok, the most basic case works:

```
λ pip install pypandoc
[...]
λ python -c "import pypandoc; print(pypandoc.convert('# Headline', to='html', format='md'))"
<h1 id="headline">Headline</h1>
```

:-)

Now lets see how the wheels and conda packages work out...

**Comment by JanSchulz** [comment]
And the packages are getting in:

`pip install pypandoc` installs a wheel (at least on windows py27 64bit: https://pypi.python.org/pypi/pypandoc/ -> not all packages are build yet...)

and this works:

```
λ pandoc
Command "pandoc" not found...
λ python -c "import pypandoc; print(pypandoc.convert('# Headline', to='html', format='md'))"
<h1 id="headline">Headline</h1>
```
