### ISSUE TITLE
py35 wheel names are not platform specific...

### ISSUE THREAD

**Issue by JanSchulz** [bebraw/pypandoc#78]
This due to the trick of overwriting the pure lib attribute doesn't work anymore as bdist_wheel doesn't use it anymore on 3.5...

I deleted the packages from PyPI so that they are hopefully not used yet... (if the users have a pandoc install, it doesn't matter..)

I've a patch (currentlx testing) and uploaded newly built py35 packages for win (funnily mac wasn't affected?). As we currently only have readme and setup.py fixes, I don't think we need a new release.

**Comment by bebraw** [comment]
Alright. Do as you see the best.

I won't be online a lot during the next few days but I'll try to comment if something comes up. :)
