### ISSUE TITLE
Problem with parsing of format names

### ISSUE THREAD

**Issue by rossant** [bebraw/pypandoc#87]
There seems to be a minor parsing problem in `twiki` with `get_pandoc_formats()`:

`['commonmark', 'docbook', 'docx', 'epub', 'haddock', 'html', 'json', 'latex', 'markdown', 'markdown_github', 'markdown_mmd', 'markdown_phpextra', 'markdown_strict', 'mediawiki', 'native', 'odt', 'opml', 'org', 'rst', 't2t', 'textile', "twiki                 [ only Pandoc's JSON version of native AST]"]`

**Comment by bebraw** [comment]
Yeah. It chokes on those brackets. Do you want to PR a fix?

**Comment by rossant** [comment]
thanks @bebraw you beat me to it!
