### ISSUE TITLE
Incorrect path in appened to pandoc search_paths

### ISSUE THREAD

**Issue by pafcu** [bebraw/pypandoc#94]
pypandoc attempts to search for /usr/bin/pandoc, but accidentally just adds /usr/bin to the search_paths in the _ensure_pandoc_path() function. The problematic line is https://github.com/bebraw/pypandoc/blob/master/pypandoc/__init__.py#L310.

This is only a big problem if /usr/bin is not in your PATH, but it does result in some diagnostic error messages being printed (since subprocess.Popen attempts to execute a directory).

The solution is to further append the binary name ('pandoc') to the path.

**Comment by janschulz** [comment]
Thanks, fix is incoming...
